### ISSUE TITLE
2 related site

### ISSUE THREAD

**Issue by koke2c95** [holodata/awesome-vtuber#1]
[VTuber Chat Trends ](https://www.vtuber-ct.net)
[にじさんじコメント検索](https://comment2434.com/)

**Comment by uetchy** [comment]
Thank you @huaji0353.
[Added](https://github.com/holodata/awesome-vtuber-analysis/commit/7bbaec879a2c36633b925b74700694f425f3cd82).

**Comment by koke2c95** [comment]
sorry to interrupt you , by the way

can we build a "vtuber profile" image dataset ? ,crawling from official site , example : [2434 liver](https://itsukaralink.jp), [holo liver](https://hololive.tv)
or from these vtuber wiki [vtuber-post](https://vtuber-post.com) , [v-data](https://v-data.info) , and more
but seem these wiki using low-resolution rescaled profile

befor we have these face dataset
[getchu face](https://www.kaggle.com/splcher/animefacedataset)
[gochiusa face](https://kaggle.com/rignak/gochiusa-faces)
[characters face](https://github.com/grapeot/Danbooru2018AnimeCharacterRecognitionDataset)
[animation face](https://www.kaggle.com/arnaud58/selfie2anime)
[large-scale wild anime draw face](https://www.gwern.net/Crops)
[manga face](http://www.manga109.org/en/download)

now add a vtuber profile face will more rich the **AnimeResearch** !

**Comment by uetchy** [comment]
@huaji0353 Seems fun to me. That'll be like CelebA but for vtubers.
I could be helpful on writing YouTube and website scraper, but am not familiar with other platforms like bilibili. Maybe we could help each other for this part (and labelling part as well).

Plus I'm wondering if we could collaborate under holodata org. Eventually, I want holodata to be home for various vtuber-related data science projects, and the profile image dataset is a perfect fit.
For the dataset itself, if you are willing to lead this project, you can just publish it on Kaggle with your account.

Since I'm actively working on [this project](https://github.com/holodata/deck) and my thesis right now, I hope you'd take the lead of the project!

**Comment by koke2c95** [comment]
RM
